@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzQ4NmMzOTI5ZmJiNjEwNDk3Mzc4OWUiLCJub21lIjoiQWRtaW5zdHJhZG9yIE9yaWdpbmFsIiwiaWF0IjoxNjY5MjU5MTI0LCJleHAiOjE2NzI4NTkxMjR9.8sopTwiNueINM1C9tROon-wyPEVVyUC0g8sjL5PmY1Q
//////////////////////////////////////////////////////////////////////
# Obter a lista de usuários
GET http://localhost:3000/api/usuarios
Content-Type: application/json
x-auth-token: {{authToken}}
###
//////////////////////////////////////////////////////////////////////
# Inserir novo usuário
POST http://localhost:3000/api/usuarios
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "nome": "Teste", 
    "cpf": "0101010101",
    "dataNascimento": "12/05/2002",
    "email": "123@123",
    "senha": "0123456789"
}
###
//////////////////////////////////////////////////////////////////////
# Alterar usuário
PUT http://localhost:3000/api/usuarios
Content-Type: application/json
x-auth-token: {{authToken}}

{
    "_id": "637eddee4f35444cd09e4155",
    "nome": "Usuário anonimizado",
    "cpf": "00000000000",
    "dataNascimento": "31/12/1999",
    "email": "usuario@anonimizado.com",
    "senha": "637eddee4f35444cd09e4155",
}

###
//////////////////////////////////////////////////////////////////////
# Excluir um usuário
DELETE http://localhost:3000/api/usuarios/63485679f3c28497a0b31810
Content-Type: application/json
x-auth-token: {{authToken}}
###
//////////////////////////////////////////////////////////////////////
# Obter pelo id de usuário
GET http://localhost:3000/api/usuarios/63474acabf2d6fa6e50b08b0
Content-Type: application/json
x-auth-token: {{authToken}}
###
//////////////////////////////////////////////////////////////////////
# Obter usuários filtrando
GET http://localhost:3000/api/usuarios/filtro/admin
Content-Type: application/json
x-auth-token: {{authToken}}
###
//////////////////////////////////////////////////////////////////////

# Autenticação de usuário
POST http://localhost:3000/api/login
Content-Type: application/json

{
 "email": "admin@admin",
 "senha": "admin"
}
###