//////////////////////////////////////////////////////////////////////
# Obter a lista de lojas
GET http://localhost:3000/api/lojas
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Inserir nova loja
POST http://localhost:3000/api/lojas
Content-Type: application/json

{
    "nomeFantasia": "Magasdsazine Luiza", 
    "url": "https://www.magaziasdasneluiza.com.br/"
}
###
//////////////////////////////////////////////////////////////////////
# Alterar loja
PUT http://localhost:3000/api/lojas
Content-Type: application/json

{
    "_id": "63474c47936c605afd965dbf",
    "loja_nomeFantasia": "Amazon Brasil", 
    "loja_url": "https://www.amazon.com.br/amazon-brasil"
}
###
//////////////////////////////////////////////////////////////////////
# Excluir um usuário
DELETE http://localhost:3000/api/lojas/6347531e936c605afd965dd2
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter pelo id da loja
GET http://localhost:3000/api/lojas/6347531e936c605afd965dd2
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter lojas filtrando
GET http://localhost:3000/api/lojas/filtro/amazon
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////