//////////////////////////////////////////////////////////////////////
# Obter a lista de promoções
GET http://localhost:3000/api/promocaos
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Inserir nova promoção
POST http://localhost:3000/api/promocaos
Content-Type: application/json

{
    "titulo": "Redmi Note 9", 
    "descricao": "Cupom imperdível!",
    "preco": "1.100",
    "url": "https://www.amazon.com.br/redmi-note-9",
    "cupom": "200ZON",
    "loja_id": "63474c38936c605afd965db9",
    "usuario_id": "63474bd2936c605afd965db2"
}
###
//////////////////////////////////////////////////////////////////////
# Alterar promoção
PUT http://localhost:3000/api/promocaos
Content-Type: application/json

{
    "_id": "6347544395606fff46b1f871",
    "titulo": "Redmi Note 9", 
    "descricao": "Cupom imperdível! Para todos!",
    "preco": "1.100",
    "url": "https://www.amazon.com.br/redmi-note-9",
    "cupom": "200ZON",
    "loja_id": "63474c38936c605afd965db9",
    "usuario_id": "63474bd2936c605afd965db2"
}
###
//////////////////////////////////////////////////////////////////////
# Excluir uma promoção
DELETE http://localhost:3000/api/promocaos/634754c995606fff46b1f880
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter pelo id da promoção
GET http://localhost:3000/api/promocaos/6347544395606fff46b1f871
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter promoções filtrando
GET http://localhost:3000/api/promocaos/filtro/Red

Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter promoções filtrando pela Loja
GET http://localhost:3000/api/promocaos/loja/63474c38936c605afd965db9
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////