//////////////////////////////////////////////////////////////////////
# Obter a lista de tipos de usuários
GET http://localhost:3000/api/tpusuarios
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Inserir novo tipo de usuário
POST http://localhost:3000/api/tpusuarios
Content-Type: application/json

{
    "tipo_descricao": "ComumTeste"
}
###
//////////////////////////////////////////////////////////////////////
# Alterar um tipo de usuário
PUT http://localhost:3000/api/tpusuarios
Content-Type: application/json

{
    "_id": "63212085c2b1b3898784eb07",
    "tipo_descricao": "Teste Mudado"
}
###
//////////////////////////////////////////////////////////////////////
# Excluir um tipo de usuário
DELETE http://localhost:3000/api/tpusuarios/63462e07a247914e20dacc0e
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter pelo id do tipo de usuário
GET http://localhost:3000/api/tpusuarios/63212085c2b1b3898784eb07
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter tipos de usuário filtrando
GET http://localhost:3000/api/tpusuarios/filtro/mudado
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////