//////////////////////////////////////////////////////////////////////
# Obter a lista de usuários
GET http://localhost:3000/api/usuarios
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Inserir novo usuário
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nome": "Admin", 
    "cpf": "00000000000",
    "dataNascimento": "12/05/2002",
    "email": "admin@admin",
    "senha": "admin"
}
###
//////////////////////////////////////////////////////////////////////
# Alterar usuário
PUT http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "_id": "63474acabf2d6fa6e50b08b0",
    "nome": "Admin", 
    "cpf": "00000",
    "dataNascimento": "12/05/2002",
    "email": "admin@admineditado",
    "senha": "admin"
}
###
//////////////////////////////////////////////////////////////////////
# Excluir um usuário
DELETE http://localhost:3000/api/usuarios/63474acabf2d6fa6e50b08b0
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter pelo id de usuário
GET http://localhost:3000/api/usuarios/63474acabf2d6fa6e50b08b0
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////
# Obter usuários filtrando
GET http://localhost:3000/api/usuarios/filtro/admin
Content-Type: application/json
###
//////////////////////////////////////////////////////////////////////